### ISSUE TITLE
Hosts file location resolution

### ISSUE THREAD

**Issue by Decencies** [uranometrical/openmantleproxy#1]
Referring to: https://github.com/uranometrical/openmantleproxy/blob/cd6cb77c47ea681bb17a5fe862287e9a559c6e9e/src/main.rs#L120

Windows provides a registry key for the `hosts` file.

Under:
`\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters`
-> `DataBasePath`

This will default to a `REG_EXPAND_SZ` value of `%SystemRoot%\System32\drivers\etc`.

**Comment by steviegt6** [comment]
Thanks for this, had been looking for an unhardcoded solution for a bit.
